<!-- Add Vessel Modal - #addVessel -->
<div class="modal fade" id="addVessel" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<form method="POST" action="<?php echo $this->url(array(), 'VesselAdd'); ?>" enctype="multipart/form-data">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span class="hubitat cross-lg-bold" aria-hidden="true"></span>
					</button>
					<h4>Add New Vessel</h4>
				</div>
				<div class="modal-body md">
					<div class="module-400">
						<div class="image">
							<img src="content/images/profile/md/empty.png">
							<a href="javascript:void(0)" onclick="$('#changeProfileImageModal').click();">Change Image</a>
							<input type="file" class="form-control-file" name="ProfileImage" id="changeProfileImageModal">
						</div>
						<div class="content">
							<div class="form-group row">
								<label for="officeName" class="col-sm-3 col-form-label">Name</label>
								<div class="col-sm-9">
									<input class="form-control" type="text"  name="Name" id="officeName">
								</div>
							</div>
							<div class="form-group row">
								<label for="officeShortName" class="col-sm-3 col-form-label">Flag</label>
								<div class="col-sm-9">
									<input class="form-control" type="text"  name="Flag" id="officeShortName">
								</div>
							</div>
							<div class="form-group row">
								<label for="IMO" class="col-sm-3 col-form-label">IMO</label>
								<div class="col-sm-9">
									<input class="form-control" type="text" id="IMO" name="IMO" >
								</div>
							</div>
							<div class="form-group row">
								<label for="officePhone" class="col-sm-3 col-form-label">Phone</label>
								<div class="col-sm-9">
									<input class="form-control" type="tel" name="Phone" id="officePhone" >
								</div>
							</div>
							<div class="form-group row">
								<label for="Class" class="col-sm-3 col-form-label">Class</label>
								<div class="col-sm-9">
									<input class="form-control" type="text" name="Class" id="Class" >
								</div>
							</div>
							<div class="form-group row">
								<label for="Owner" class="col-sm-3 col-form-label">Owner</label>
								<div class="col-sm-9">
									<input class="form-control" type="text" name="Owner" id="Owner" >
								</div>
							</div>
						</div><!-- /.content -->
					</div><!-- /.module-400 -->

				</div><!-- /.modal-body -->
				<div class="module-499">
					<div class="module-499-wrapper">
						<input type="submit" role="button" class="module-499-btn left cancel" data-dismiss="modal" aria-label="Close" value="Cancel">
						<input type="submit" role="button" class="module-499-btn right save" value="SAVE">
					</div><!-- /.module-499-wrapper -->
				</div><!-- /.module-499 -->
			</div><!-- /.modal-content -->
		</form>
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->