<!-- Add Agency Modal - #addAgency -->
<div class="modal fade" id="addAgency" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<form method="POST" action="<?php echo $this->url(array(), 'AgencyAdd'); ?>" enctype="multipart/form-data">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span class="hubitat cross-lg-bold" aria-hidden="true"></span>
					</button>
					<h4>Add New Agency</h4>
				</div>
				<div class="modal-body md">
					<div class="module-400">
						<div class="image">
							<img src="content/images/profile/md/empty.png">
							<a href="javascript:void(0)" onclick="$('#changeProfileImageModal').click();">Change Image</a>
							<input type="file" class="form-control-file" name="ProfileImage" id="changeProfileImageModal">
						</div>
						<div class="content">

							<div class="form-group row">
								<label for="profileNameModal" class="col-sm-3 col-form-label">Name</label>
								<div class="col-sm-9">
									<input class="form-control" name="Name" type="text" value="" id="profileNameModal">
								</div>
							</div>

							<div class="form-group row">
								<label for="profileEmailModal" class="col-sm-3 col-form-label">Email</label>
								<div class="col-sm-9">
									<input class="form-control" name="Email" type="email" value="" id="profileEmailModal">
								</div>
							</div>

							<div class="form-group row">
								<label for="profilePhoneModal" class="col-sm-3 col-form-label">Phone</label>
								<div class="col-sm-9">
									<input class="form-control" type="tel" value="" id="profilePhoneModal" name="Phone">
								</div>
							</div>
							<div class="form-group row">
								<label for="profilePhoneModal" class="col-sm-3 col-form-label">Address</label>
								<div class="col-sm-9">
									<textarea class="form-control" id="officeAddress" name="Address" rows="3"></textarea>
								</div>
							</div>
							<div class="form-group row">
								<label for="officePhone" class="col-sm-3 col-form-label">Person</label>
								<div class="col-sm-9">
									<input class="form-control" type="text" name="Person" id="officePhone">
								</div>
							</div>
						</div><!-- /.content -->
					</div><!-- /.module-400 -->

				</div><!-- /.modal-body -->
				<div class="module-499">
					<div class="module-499-wrapper">
						<input type="submit" role="button" class="module-499-btn left cancel" data-dismiss="modal" aria-label="Close" value="Cancel">
						<input type="submit" role="button" class="module-499-btn right save" value="SAVE">
					</div><!-- /.module-499-wrapper -->
				</div><!-- /.module-499 -->
			</div><!-- /.modal-content -->
		</form>
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->