<!-- Add Agency Modal - #addAgency -->
<div class="modal fade" id="addWorkOrderModal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<form method="POST" action="<?php echo $this->url(array(), 'AgencyAdd'); ?>" enctype="multipart/form-data">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span class="hubitat cross-lg-bold" aria-hidden="true"></span>
					</button>
					<h4>Add Work Order</h4>
				</div>
			</div><!-- /.modal-content -->
		</form>
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->