<?php echo $this->render('partials/modals/delete-agency.phtml'); ?>
<?php echo $this->render('partials/modals/add-agency.phtml'); ?>
<li class="second-sidebar">
	<div class="second-sidebar-header">
		<div class="second-sidebar-title">
			<h3><?php echo $this->moduleTitle; ?></h3>
		</div>
		<div class="second-sidebar-actions">
			<a class="search" data-toggle="collapse" href="#collapseSearch" aria-expanded="false" aria-controls="collapseSearch"><span class="hubitat magnifier-lg"></span></a>
			<a href="javascript:void(0)" class="add-item" data-toggle="modal" data-target="#addAgency"><span class="hubitat plus"></span></a>
		</div>
	</div>
	<div class="second-sidebar-wrapper">
		<div class="list-101">
			<div class="second-sidebar-search collapse" id="collapseSearch">
				<div class="form-group">
					<input type="text" class="form-control search" data-target="list-container" id="secondSidebarSearch" aria-describedby="searchHelp" placeholder="Search for <?php echo $this->moduleTitle; ?>">
					<span id="searchHelp" class="form-text text-muted">Start typing to filter agency results.</span>
				</div>
			</div>

			<!-- İsme göre sıralanacak -->
			<div class="list-container">
				<?php if(isset($this->oAgencyList)){ ?>
					<?php foreach($this->oAgencyList as $listItem){ ?> 
						<a href="<?php echo $this->url(array('agencyId'=>$listItem['_id']), 'Agency'); ?>" title="Details" class="list-101-item <?php echo ($listItem['_id'] == $this->oAgency['_id'] ? 'active' : ''); ?>">
							<?php echo $listItem['Name']; ?>
						</a>
					<?php } ?>
				<?php } ?>
			</div>
		</div>
	</div>
</li><!-- /.second-sidebar -->

<li class="main-content">
	<div class="main-content-header">
		<div class="module-300">
			<a href="<?php echo $this->url(array(), 'Overview'); ?>" title="Overview">Overview</a>
			<span class="hubitat right-arrow-bold divider"></span>
			<a href="<?php echo $this->url(array(), 'Agencies'); ?>" title="Agencies">Agencies</a>
			<span class="hubitat right-arrow-bold divider"></span>
			<span class="current-page"><?php echo $this->oAgency['Name']; ?></span>
		</div><!-- /.module-300 -->
		<?php echo $this->render('partials/user-toolbar.phtml'); ?>
	</div><!-- /.main-content-header -->
	<form method="POST" action="" enctype="multipart/form-data">
		<div class="main-content-wrapper">
			<div class="module md">
				<div class="module-header dropdown">
					<h3>Agencies</h3>
					<a href="javascript:void(0)" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<span class="hubitat settings" ></span>
					</a>
					<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
						<a class="dropdown-item danger" href="javascript:void(0)" data-toggle="modal" data-target="#deleteAgency">Delete Agency</a>
					</div>
				</div>
				<div class="module-content">
					<div class="module-400">
						<div class="image">
							<img src="content/images/profile/md/<?php echo $this->oAgency['Avatar']; ?>" id="profileImage">
							<a href="javascript:void(0)" onclick="$('#changeProfileImage').click();">Change Image</a>
							<input type="file" class="form-control-file" name="ProfileImage" id="changeProfileImage">
						</div>
						<div class="content">
							<div class="form-group row">
								<label for="officeName" class="col-sm-3 col-form-label">Name</label>
								<div class="col-sm-9">
									<input class="form-control" type="text" value="<?php echo $this->oAgency['Name']; ?>" name="Name" id="officeName">
								</div>
							</div>
							<div class="form-group row">
								<label for="Email" class="col-sm-3 col-form-label">Email</label>
								<div class="col-sm-9">
									<input class="form-control" type="email" value="<?php echo $this->oAgency['Email']; ?>" name="Email" id="Email">
								</div>
							</div>
							<div class="form-group row">
								<label for="IMO" class="col-sm-3 col-form-label">Address</label>
								<div class="col-sm-9">
									<textarea class="form-control" id="officeAddress" name="Address" rows="3"><?php echo $this->oAgency['Address']; ?></textarea>
								</div>
							</div>
							<div class="form-group row">
								<label for="officePhone" class="col-sm-3 col-form-label">Phone</label>
								<div class="col-sm-9">
									<input class="form-control" type="tel" name="Phone" id="officePhone" value="<?php echo $this->oAgency['Phone']; ?>">
								</div>
							</div>
							<div class="form-group row">
								<label for="officePhone" class="col-sm-3 col-form-label">Person</label>
								<div class="col-sm-9">
									<input class="form-control" type="text" name="Person" id="officePhone" value="<?php echo $this->oAgency['Person']; ?>">
								</div>
							</div>
							
						</div><!-- /.content -->
					</div><!-- /.module-400 -->
				</div><!-- /.module-content -->
			</div>
		</div><!-- /.main-content-wrapper -->


		<div class="module-499">
			<div class="module-499-wrapper">
				<input type="submit" role="button" class="module-499-btn left cancel" data-dismiss="modal" aria-label="Close" value="Cancel">
				<input type="submit" role="button" class="module-499-btn right save" value="SAVE">
			</div><!-- /.module-499-wrapper -->
		</div><!-- /.module-499 -->
	</form>

</li><!-- /.main-content -->