<!DOCTYPE html>
<html>
	<head>
		<base href="<?php echo $this->Assets()->baseUrl(); ?>"/>	
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>Welcome to Hubitat</title>

		<link rel="stylesheet" type="text/css" href="dist/css/bootstrap/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="dist/css/main.css">
		<link rel="icon" type="image/png" href="content/images/favicon.png" />
		<!-- for iOS devices -->
		<meta name="apple-mobile-web-app-title" content="Hubitat" />
		<link rel="apple-touch-icon-precomposed" href="content/images/apple-touch-icon.png" />
	</head>

	<body>
		<div class="module-1-wrapper">
			<div class="module-1">
				<form method="POST" action="<?php echo $this->url(); ?>">
					<div class="module-1-item-wrapper">
						<div class="module-1-item logo">
							<img src="content/images/hubitat-logo-vertical.svg" alt="Hubitat Logo">
						</div><!-- /.module-1-item logo -->
						<h3>Reset your password</h3>
						<?php if(isset($this->user)){ ?>
							<div class="module-1-item login-form">
								<div class="form-group">
									<label for="password">New Password</label>
									<input type="password" class="form-control" id="password" aria-describedby="Password" value="" name="new_password" />
								</div>
								<div class="form-group">
									<label for="reenterpassword">Reenter Password</label>
									<input type="password" class="form-control" id="reenterpassword" aria-describedby="reenterpassword" value="" name="new_password_again" />
								</div>
							</div><!-- /.module-1-item login-form -->
							<div class="module-1-item buttons">
								<div class="module-499-wrapper">
									<input type="submit" role="button" class="module-499-btn right save" value="CHANGE PASSWORD">
								</div>
							</div>
						<?php }else{ ?>

							<div class="module-1-item login-form">
								<strong>Error</strong><br />
								<?php if(isset($this->password_error)){ ?>
									Passwords are not same!.<br />
									<a href="javascript:history.go(-1);">Go Back</a>
								<?php }else{ ?>
									Invalid Code.<br />
									<a href="<?php echo $this->url(array(), 'Login'); ?>">Go Back to Login</a>
								<?php } ?>
							</div>
						<?php } ?>

					</div><!-- /.module-1-item-wrapper -->
				</form>
			</div><!-- /.module-1 -->
		</div><!-- /.module-1-wrapper -->

		<div class="imprint">
			<a href="imprint.html" target="_blank">Imprint</a>
			<span class="version">v2.0</span>
		</div>

		<!-- Page Scripts -->
		<script src="dist/js/jquery-2.2.1.min.js"></script>
		<script src="dist/js/bootstrap/bootstrap.min.js"></script>
		<script src="dist/js/hubitat.js"></script>
	</body>
</html>