<?php echo $this->render('partials/modals/delete-vessel.phtml'); ?>
<?php echo $this->render('partials/modals/add-vessel.phtml'); ?>
<li class="second-sidebar">
	<div class="second-sidebar-header">
		<div class="second-sidebar-title">
			<h3><?php echo $this->moduleTitle; ?></h3>
		</div>
		<div class="second-sidebar-actions">
			<a class="search" data-toggle="collapse" href="#collapseSearch" aria-expanded="false" aria-controls="collapseSearch"><span class="hubitat magnifier-lg"></span></a>
			<a href="javascript:void(0)" class="add-item" data-toggle="modal" data-target="#addVessel"><span class="hubitat plus"></span></a>
		</div>
	</div>
	<div class="second-sidebar-wrapper">
		<div class="list-101">
			<div class="second-sidebar-search collapse" id="collapseSearch">
				<div class="form-group">
					<input type="text" class="form-control search" data-target="list-container" id="secondSidebarSearch" aria-describedby="searchHelp" placeholder="Search for <?php echo $this->moduleTitle; ?>">
					<span id="searchHelp" class="form-text text-muted">Start typing to filter vessel results.</span>
				</div>
			</div>

			<!-- İsme göre sıralanacak -->
			<div class="list-container">
				<?php if(isset($this->oVesselList)){ ?>
					<?php foreach($this->oVesselList as $listItem){ ?> 
						<a href="<?php echo $this->url(array('vesselId'=>$listItem['_id']), 'Vessel'); ?>" title="Details" class="list-101-item <?php echo ($listItem['_id'] == $this->oVessel['_id'] ? 'active' : ''); ?>">
							<?php echo $listItem['Name']; ?>
						</a>
					<?php } ?>
				<?php } ?>
			</div>
		</div>
	</div>
</li><!-- /.second-sidebar -->

<li class="main-content ">
	<div class="main-content-header">
		<div class="module-300">
			<a href="<?php echo $this->url(array(), 'Overview'); ?>" title="Overview">Overview</a>
			<span class="hubitat right-arrow-bold divider"></span>
			<a href="<?php echo $this->url(array(), 'Vessels'); ?>" title="Vessels">Vessels</a>
			<span class="hubitat right-arrow-bold divider"></span>
			<span class="current-page"><?php echo $this->oVessel['Name']; ?>)</span>
		</div><!-- /.module-300 -->
		<?php echo $this->render('partials/user-toolbar.phtml'); ?>
	</div><!-- /.main-content-header -->
	<form method="POST" action="" enctype="multipart/form-data">
		<div class="main-content-wrapper">
			<div class="module md">
				<div class="module-header dropdown">
					<h3>Vessel</h3>
					<a href="javascript:void(0)" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<span class="hubitat settings" ></span>
					</a>
					<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
						<a class="dropdown-item danger" href="javascript:void(0)" data-toggle="modal" data-target="#deleteVessel">Delete Vessel</a>
					</div>
				</div>
				<div class="module-content">
					<div class="module-400">
						<div class="image">
							<img src="content/images/profile/md/<?php echo $this->oVessel['Avatar']; ?>">
							<a href="javascript:void(0)" onclick="$('#changeOfficeImage').click();">Change Image</a>
							<input type="file" class="form-control-file" name="ProfileImage" id="changeOfficeImage">
						</div>
						<div class="content">
							<div class="form-group row">
								<label for="officeName" class="col-sm-3 col-form-label">Name</label>
								<div class="col-sm-9">
									<input class="form-control" type="text" value="<?php echo $this->oVessel['Name']; ?>" name="Name" id="officeName">
								</div>
							</div>
							<div class="form-group row">
								<label for="officeShortName" class="col-sm-3 col-form-label">Flag</label>
								<div class="col-sm-9">
									<input class="form-control" type="text" value="<?php echo $this->oVessel['Flag']; ?>" name="Flag" id="officeShortName">
								</div>
							</div>
							<div class="form-group row">
								<label for="IMO" class="col-sm-3 col-form-label">IMO</label>
								<div class="col-sm-9">
									<input class="form-control" type="text" id="IMO" name="IMO" value="<?php echo $this->oVessel['IMO']; ?>">
								</div>
							</div>
							<div class="form-group row">
								<label for="officePhone" class="col-sm-3 col-form-label">Phone</label>
								<div class="col-sm-9">
									<input class="form-control" type="tel" name="Phone" id="officePhone" value="<?php echo $this->oVessel['Phone']; ?>">
								</div>
							</div>
							<div class="form-group row">
								<label for="Class" class="col-sm-3 col-form-label">Class</label>
								<div class="col-sm-9">
									<input class="form-control" type="text" name="Class" id="Class" value="<?php echo $this->oVessel['Class']; ?>">
								</div>
							</div>
							<div class="form-group row">
								<label for="Owner" class="col-sm-3 col-form-label">Owner</label>
								<div class="col-sm-9">
									<input class="form-control" type="text" name="Owner" id="Owner" value="<?php echo $this->oVessel['Owner']; ?>">
								</div>
							</div>

						</div><!-- /.content -->
					</div><!-- /.module-400 -->
				</div><!-- /.module-content -->
			</div>
		</div><!-- /.main-content-wrapper -->


		<div class="module-499">
			<div class="module-499-wrapper">
				<input type="submit" role="button" class="module-499-btn left cancel" data-dismiss="modal" aria-label="Close" value="Cancel">
				<input type="submit" role="button" class="module-499-btn right save" value="SAVE">
			</div><!-- /.module-499-wrapper -->
		</div><!-- /.module-499 -->
	</form>

</li><!-- /.main-content -->