<div>
	<ul class="list-main">

	<li class="first-sidebar left-menu">
		<div class="brand">
			<img src="content/images/hubitat-logo.svg" alt="Hubitat - Maritime Certification EcoSystem">
		</div>
		<div class="first-sidebar-wrapper">
			<ul class="list-100">
				<li class="list-100-item">
					<a href="javascript:void(0);" title="Overview">
						<span class="hubitat hexagon"></span>
						<span class="name">Overview</span>
					</a>
				</li>
				<li class="list-100-item">
					<a href="<?php echo $this->url(array(), 'WorkOrders'); ?>" title="Work Orders">
						<span class="hubitat file-stack"></span>
						<span class="name">Work Orders</span>
					</a>
				</li>
				<li class="list-100-item">
					<a href="javascript:void(0);" title="Analytics">
						<span class="hubitat chart"></span>
						<span class="name">Analytics</span>
					</a>
				</li>
			</ul><!-- /.list-100 -->
			<ul class="list-100">
				<div class="list-100-header">
					<span class="name">ACCOUNTS</span>
				</div>
				<li class="list-100-item">
					<a href="<?php echo $this->url(array(), 'Crews'); ?>" title="Crews">
						<span class="hubitat crew-2"></span>
						<span class="name">Crews</span>
					</a>
				</li>
				<li class="list-100-item">
					<a href="<?php echo $this->url(array(), 'Offices'); ?>" title="Offices">
						<span class="hubitat pin"></span>
						<span class="name">Offices</span>
					</a>
				</li>
				<li class="list-100-item">
					<a href="<?php echo $this->url(array(), 'Vessels'); ?>" title="Vessels">
						<span class="hubitat ship"></span>
						<span class="name">Vessels</span>
					</a>
				</li>
				<li class="list-100-item">
					<a href="<?php echo $this->url(array(), 'Agencies'); ?>" title="Agencies">
						<span class="hubitat handshake"></span>
						<span class="name">Agencies</span>
					</a>
				</li>
			</ul><!-- /.list-100 -->
			<ul class="list-100">
				<div class="list-100-header">
					<span class="name">FILES</span>
				</div>
				<li class="list-100-item tight">
					<a href="<?php echo $this->url(array('type'=>'class'), 'Files'); ?>" title="Class">
						<span class="name">Class</span>
					</a>
				</li>
				<li class="list-100-item tight">
					<a href="<?php echo $this->url(array('type'=>'manufacturer'), 'Files'); ?>" title="Manufacturer">
						<span class="name">Manufacturer</span>
					</a>
				</li>
				<li class="list-100-item tight">
					<a href="<?php echo $this->url(array('type'=>'port-authority'), 'Files'); ?>" title="Port Authority">
						<span class="name">Port Authority</span>
					</a>
				</li>
				<li class="list-100-item tight">
					<a href="<?php echo $this->url(array('type'=>'check-list'), 'Files'); ?>" title="Check List">
						<span class="name">Check List</span>
					</a>
				</li>
				<li class="list-100-item tight">
					<a href="<?php echo $this->url(array('type'=>'iso'), 'Files'); ?>" title="ISO">
						<span class="name">ISO</span>
					</a>
				</li>
				<li class="list-100-item tight">
					<a href="<?php echo $this->url(array('type'=>'other'), 'Files'); ?>" title="Other">
						<span class="name">Other</span>
					</a>
				</li>
			</ul><!-- /.list-100 -->
		</div>
	</li><!-- /.first-sidebar -->

	<?php if(isset($this->moduleTitle)){ ?>
		<script>$('.left-menu span.name:contains("<?php echo $this->moduleTitle; ?>")').parent().addClass('active');</script>
	<?php } ?>
